bind r source-file ~/.tmux.conf

set-option -g default-terminal 'tmux-256color'
set-option -sa terminal-overrides ',ghostty:RGB,xterm-ghostty:RGB,tmux-256color:RGB'

set -g history-limit 10000

if-shell '[ -x /bin/zsh ]' 'set-option -g default-shell /bin/zsh; set-option -g default-command "/bin/zsh -l"'

set -g status-position top

set -g prefix2 C-a
bind C-a send-prefix -2

set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on
set -g renumber-windows on

set -g monitor-activity on
set -g visual-activity off

if -b 'command -v pbcopy > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | pbcopy"'
if -b 'command -v reattach-to-user-namespace > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | reattach-to-user-namespace pbcopy"'
if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'
if -b 'command -v clip.exe > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | clip.exe"'
if -b '[ -c /dev/clipboard ]' 'bind y #run -b "tmux save-buffer - > /dev/clipboard"'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'NHDaly/tmux-better-mouse-mode'

bind -T copy-mode-vi WheelUpPane send-keys -X -N 1 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 1 scroll-down

bind -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down

bind-key m if-shell "tmux show-options -g mouse | grep -q 'on'" \
    "set -g mouse off; display 'Mouse OFF'" \
    "set -g mouse on; display 'Mouse ON'"

run '~/.tmux/plugins/tpm/tpm'
